version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_USER_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASS}

  wiki:
    image: requarks/wiki:2
    restart: always
    depends_on:
      - db
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_USER_PASS}
      DB_NAME: 4{DB_DATABASE}
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data