version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASS}

  gogs:
    image: gogs/gogs
    restart: always
    depends_on:
      - db
    environment:
      USER_UID: 1000
      USER_GID: 1000
      DB_TYPE: mysql
      DB_HOST: db:3306
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_USER_PASS}
      DISABLE_REGISTRATION: "false"
      REQUIRE_SIGNIN_VIEW: "true"
    ports:
      - "3001:3000"
      - "3022:22"
