version: "3.8"
services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASS}
    logging:
      driver: "none"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    # image: ghcr.io/requarks/wiki:2
    image: ghcr.io/requarks/wiki:3.0.0-alpha.334
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_USER_PASS}
    restart: unless-stopped
    ports:
      - "3080:3000"

volumes:
  db-data: