version: "3.8"

services:

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASS}
    networks:
      wiki-net:
        ipv4_address: 10.7.0.2

  wiki:
    image: ghcr.io/requarks/wiki:2
    restart: always
    # volumes:
    #   - wiki-data:/wiki/data/content
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_USER_PASS}
      DB_NAME: ${DB_DATABASE}
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    networks:
      wiki-net:
        ipv4_address: 10.7.0.3

networks:
  wiki-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.7.0.0/16
         gateway: 10.7.0.1

volumes:
  db-data:
  # wiki-data: